# GWASLAB VISUALIZATIONS

### Import data and libraries

In [1]:
import gwaslab as gl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
repeat_test1 = pd.read_csv("/home/maria/git/SOROLLA/REPEATED/ldsc_test1/ldsc_correlation_test1.csv")
print("Test repeat 1")
display(repeat_test1.head())

Test repeat 1

,label_1,id_1,label_2,id_2,rg,se,z,p,h2_obs,h2_obs_se,h2_int,h2_int_se,gcov_int,gcov_int_se
0,ADHD-sex-M1,GCST90275148,depression-symptoms,GCST003769,0.4590,0.0511,8.9808,2.686900e-19,0.0384,0.0033,1.0159,0.0072,0.0119,0.0061
1,crc-benign-neoplasm,GCST90042860,lung-carcinoma-1,GCST004748,0.1572,0.0701,2.2414,2.500000e-02,0.0841,0.0167,1.0496,0.0119,0.0101,0.0053
2,crc-benign-neoplasm,GCST90042860,non-epithelial-carcinoma,GCST90041830,-0.0125,0.0704,-0.1768,8.597000e-01,0.0169,0.0027,1.0279,0.0122,0.0173,0.0054
3,lung-carcinoma-1,GCST004748,non-epithelial-carcinoma,GCST90041830,0.2036,0.0615,3.3136,9.000000e-04,0.0173,0.0028,1.0240,0.0122,-0.0007,0.0059
4,depression-symptoms,GCST003769,bcc-1,GCST90013410,-0.0442,0.0482,-0.9176,3.589000e-01,0.0322,0.0046,1.0645,0.0186,-0.0031,0.0062

In [3]:
repeat_test2 = pd.read_csv("/home/maria/git/SOROLLA/REPEATED/ldsc_test2/ldsc_correlation_test2.csv")
print("Test repeat 2")
display(repeat_test2.head())

Test repeat 2

,label_1,id_1,label_2,id_2,rg,se,z,p,h2_obs,h2_obs_se,h2_int,h2_int_se,gcov_int,gcov_int_se
0,ADHD-sex-M1,GCST90275148,depression-symptoms,GCST003769,0.4590,0.0511,8.9808,2.686900e-19,0.0384,0.0033,1.0159,0.0072,0.0119,0.0061
1,crc-benign-neoplasm,GCST90042860,lung-carcinoma-1,GCST004748,0.1572,0.0701,2.2414,2.500000e-02,0.0841,0.0167,1.0496,0.0119,0.0101,0.0053
2,crc-benign-neoplasm,GCST90042860,non-epithelial-carcinoma,GCST90041830,-0.0125,0.0704,-0.1768,8.597000e-01,0.0169,0.0027,1.0279,0.0122,0.0173,0.0054
3,lung-carcinoma-1,GCST004748,non-epithelial-carcinoma,GCST90041830,0.2036,0.0615,3.3136,9.000000e-04,0.0173,0.0028,1.0240,0.0122,-0.0007,0.0059
4,depression-symptoms,GCST003769,bcc-1,GCST90013410,-0.0442,0.0482,-0.9176,3.589000e-01,0.0322,0.0046,1.0645,0.0186,-0.0031,0.0062

In [4]:
repeat_test3 = pd.read_csv("/home/maria/git/SOROLLA/REPEATED/ldsc_test3/ldsc_correlation_test3.csv")
print("Test repeat 3")
display(repeat_test3.head())

Test repeat 3

,label_1,id_1,label_2,id_2,rg,se,z,p,h2_obs,h2_obs_se,h2_int,h2_int_se,gcov_int,gcov_int_se
0,ADHD-sex-M1,GCST90275148,depression-symptoms,GCST003769,0.4590,0.0511,8.9808,2.686900e-19,0.0384,0.0033,1.0159,0.0072,0.0119,0.0061
1,crc-benign-neoplasm,GCST90042860,lung-carcinoma-1,GCST004748,0.1572,0.0701,2.2414,2.500000e-02,0.0841,0.0167,1.0496,0.0119,0.0101,0.0053
2,crc-benign-neoplasm,GCST90042860,non-epithelial-carcinoma,GCST90041830,-0.0125,0.0704,-0.1768,8.597000e-01,0.0169,0.0027,1.0279,0.0122,0.0173,0.0054
3,lung-carcinoma-1,GCST004748,non-epithelial-carcinoma,GCST90041830,0.2036,0.0615,3.3136,9.000000e-04,0.0173,0.0028,1.0240,0.0122,-0.0007,0.0059
4,depression-symptoms,GCST003769,bcc-1,GCST90013410,-0.0442,0.0482,-0.9176,3.589000e-01,0.0322,0.0046,1.0645,0.0186,-0.0031,0.0062

In [8]:
repeat_test1.columns

Index(['label_1', 'id_1', 'label_2', 'id_2', 'rg', 'se', 'z', 'p', 'h2_obs',
       'h2_obs_se', 'h2_int', 'h2_int_se', 'gcov_int', 'gcov_int_se'],
      dtype='object')

In [12]:
# Merge DataFrames
merged_tests_1_2 = repeat_test1.merge(repeat_test2, on=["label_1","id_1","label_2","id_2"], suffixes=["_test1", "_test2"])
# Rename in test3 because otherwise the suffix option is not applying
repeat_test3_renamed = repeat_test3.rename(columns=lambda x: x if x in ["label_1","id_1","label_2","id_2"] else f"{x}_test3")
# Merge all three now
merged_tests = merged_tests_1_2.merge(repeat_test3_renamed, on=["label_1","id_1","label_2","id_2"])
#Save to csv file:
merged_tests.to_csv("/home/maria/git/SOROLLA/REPEATED/merged_tests_comparison.csv")
display(merged_tests.head())
display(merged_tests.columns)

,label_1,id_1,label_2,id_2,rg_test1,se_test1,z_test1,p_test1,h2_obs_test1,h2_obs_se_test1,...,rg_test3,se_test3,z_test3,p_test3,h2_obs_test3,h2_obs_se_test3,h2_int_test3,h2_int_se_test3,gcov_int_test3,gcov_int_se_test3
0,ADHD-sex-M1,GCST90275148,depression-symptoms,GCST003769,0.4590,0.0511,8.9808,2.686900e-19,0.0384,0.0033,...,0.4590,0.0511,8.9808,2.686900e-19,0.0384,0.0033,1.0159,0.0072,0.0119,0.0061
1,crc-benign-neoplasm,GCST90042860,lung-carcinoma-1,GCST004748,0.1572,0.0701,2.2414,2.500000e-02,0.0841,0.0167,...,0.1572,0.0701,2.2414,2.500000e-02,0.0841,0.0167,1.0496,0.0119,0.0101,0.0053
2,crc-benign-neoplasm,GCST90042860,non-epithelial-carcinoma,GCST90041830,-0.0125,0.0704,-0.1768,8.597000e-01,0.0169,0.0027,...,-0.0125,0.0704,-0.1768,8.597000e-01,0.0169,0.0027,1.0279,0.0122,0.0173,0.0054
3,lung-carcinoma-1,GCST004748,non-epithelial-carcinoma,GCST90041830,0.2036,0.0615,3.3136,9.000000e-04,0.0173,0.0028,...,0.2036,0.0615,3.3136,9.000000e-04,0.0173,0.0028,1.0240,0.0122,-0.0007,0.0059
4,depression-symptoms,GCST003769,bcc-1,GCST90013410,-0.0442,0.0482,-0.9176,3.589000e-01,0.0322,0.0046,...,-0.0442,0.0482,-0.9176,3.589000e-01,0.0322,0.0046,1.0645,0.0186,-0.0031,0.0062

Index(['label_1', 'id_1', 'label_2', 'id_2', 'rg_test1', 'se_test1', 'z_test1',
       'p_test1', 'h2_obs_test1', 'h2_obs_se_test1', 'h2_int_test1',
       'h2_int_se_test1', 'gcov_int_test1', 'gcov_int_se_test1', 'rg_test2',
       'se_test2', 'z_test2', 'p_test2', 'h2_obs_test2', 'h2_obs_se_test2',
       'h2_int_test2', 'h2_int_se_test2', 'gcov_int_test2',
       'gcov_int_se_test2', 'rg_test3', 'se_test3', 'z_test3', 'p_test3',
       'h2_obs_test3', 'h2_obs_se_test3', 'h2_int_test3', 'h2_int_se_test3',
       'gcov_int_test3', 'gcov_int_se_test3'],
      dtype='object')

In [9]:
# Define the base column lists
columns_correlation_base = ['label_1', 'id_1', 'label_2', 'id_2', 'rg', 'se', 'z', 'p']
columns_covariance_base = ['label_1', 'id_1', 'label_2', 'id_2', 'gcov_int', 'gcov_int_se']

# Define the suffixes
suffixes = ['test1', 'test2', 'test3']

In [10]:
# Generate the full column lists
columns_correlation = ['label_1', 'id_1', 'label_2', 'id_2'] + [f'{col}_{suffix}' for col in columns_correlation_base[4:] for suffix in suffixes]
# Generate correlation_test
correlation_test = merged_tests[columns_correlation]
# Display the df
display(correlation_test.head())
print(correlation_test.columns)

,label_1,id_1,label_2,id_2,rg_test1,rg_test2,rg_test3,se_test1,se_test2,se_test3,z_test1,z_test2,z_test3,p_test1,p_test2,p_test3
0,ADHD-sex-M1,GCST90275148,depression-symptoms,GCST003769,0.4590,0.4590,0.4590,0.0511,0.0511,0.0511,8.9808,8.9808,8.9808,2.686900e-19,2.686900e-19,2.686900e-19
1,crc-benign-neoplasm,GCST90042860,lung-carcinoma-1,GCST004748,0.1572,0.1572,0.1572,0.0701,0.0701,0.0701,2.2414,2.2414,2.2414,2.500000e-02,2.500000e-02,2.500000e-02
2,crc-benign-neoplasm,GCST90042860,non-epithelial-carcinoma,GCST90041830,-0.0125,-0.0125,-0.0125,0.0704,0.0704,0.0704,-0.1768,-0.1768,-0.1768,8.597000e-01,8.597000e-01,8.597000e-01
3,lung-carcinoma-1,GCST004748,non-epithelial-carcinoma,GCST90041830,0.2036,0.2036,0.2036,0.0615,0.0615,0.0615,3.3136,3.3136,3.3136,9.000000e-04,9.000000e-04,9.000000e-04
4,depression-symptoms,GCST003769,bcc-1,GCST90013410,-0.0442,-0.0442,-0.0442,0.0482,0.0482,0.0482,-0.9176,-0.9176,-0.9176,3.589000e-01,3.589000e-01,3.589000e-01

Index(['label_1', 'id_1', 'label_2', 'id_2', 'rg_test1', 'rg_test2',
       'rg_test3', 'se_test1', 'se_test2', 'se_test3', 'z_test1', 'z_test2',
       'z_test3', 'p_test1', 'p_test2', 'p_test3'],
      dtype='object')

In [11]:
# Generate the full column lists
columns_covariance = ['label_1', 'id_1', 'label_2', 'id_2'] + [f'{col}_{suffix}' for col in columns_covariance_base[4:] for suffix in suffixes]
# Generate the covariance_test
covariance_test = merged_tests[columns_covariance]
# Display the df
display(covariance_test.head())
print(covariance_test.columns)

,label_1,id_1,label_2,id_2,gcov_int_test1,gcov_int_test2,gcov_int_test3,gcov_int_se_test1,gcov_int_se_test2,gcov_int_se_test3
0,ADHD-sex-M1,GCST90275148,depression-symptoms,GCST003769,0.0119,0.0119,0.0119,0.0061,0.0061,0.0061
1,crc-benign-neoplasm,GCST90042860,lung-carcinoma-1,GCST004748,0.0101,0.0101,0.0101,0.0053,0.0053,0.0053
2,crc-benign-neoplasm,GCST90042860,non-epithelial-carcinoma,GCST90041830,0.0173,0.0173,0.0173,0.0054,0.0054,0.0054
3,lung-carcinoma-1,GCST004748,non-epithelial-carcinoma,GCST90041830,-0.0007,-0.0007,-0.0007,0.0059,0.0059,0.0059
4,depression-symptoms,GCST003769,bcc-1,GCST90013410,-0.0031,-0.0031,-0.0031,0.0062,0.0062,0.0062

Index(['label_1', 'id_1', 'label_2', 'id_2', 'gcov_int_test1',
       'gcov_int_test2', 'gcov_int_test3', 'gcov_int_se_test1',
       'gcov_int_se_test2', 'gcov_int_se_test3'],
      dtype='object')